DESCRIPTION = {
    1401: [
        ("Descrição", ['''Gerar permutações sempre foi um problema importante na ciência da computação. Neste problema, você terá de gerar todas as permutações de uma dada string, em ordem lexicográfica crescente. Lembre-se que seu algoritmo deve ser eficiente.''']),
        ("Entrada", ['''A primeira linha da entrada contém um inteiro n, indicando o número de strings que seguem. As próximas n linhas contém uma string cada. Cada string conterá apenas caracteres alfanuméricos, e nunca conterá espaços. O tamanho máximo de uma string é 10.''']),
        ("Saida", ['''Para cada string da entrada, imprima todas as permutações possíveis da string, em ordem lexicográfica crescente. Note que as strings devem ser tratas como Case Sensitive (isto é, letras maiúsculas são diferentes das minúsculas). Além disso, nenhuma permutação deve ser impressa mais de uma vez. Uma linha em branco deve ser impressa após cada lista de permutações.'''])
        ],
    
    1250:[
        ("Descrição", ['''Você chegou a um dos últimos chefões no novo jogo de ação 2-D de deslocamento lateral, KiloMan. O chefão tem uma arma grande que pode atirar projéteis em várias alturas. Para cada tiro, KiloMan pode ficar parado ou pular. Se ele ficar parado e o tiro estiver na altura 1 ou 2, ele será atingido. Se ele pular e o tiro estiver a uma altura maior que 2, então ele também será atingido. Caso contrário, ele não é atingido. Dada a altura de cada tiro e a sequência de pulos, quantas vezes KiloMan será atingido?''']),
        ("Entrada", ['''A entrada contém vários casos de teste. A primeira linha da entrada contém um inteiro N que indica o número de casos de teste. Cada caso de teste é composto por 3 linhas. A primeira linha contém um inteiro T (1 ≤ T ≤ 50) que indica o número de tiros. A segunda linha contém T inteiros, que representam a sequência das alturas às quais os tiros estão sendo disparados. Cada elemento da sequência será entre 1 e 7, inclusive. A terceira linha da entrada contém a string "pulos", que representa a sequência de pulos que KiloMan tentará; 'J' significa que ele irá pular e 'S' significa que ele ficará parado. Por exemplo, se o primeiro número da sequência de tiros for 3 e o primeiro caractere de "pulos" for 'J', então KiloMan pulará assim que o chefão atirar a uma altura 3 (e, portanto, ele será atingido).''']),
        ("Saída", ['''Para cada caso, seu programa deve imprimir um inteiro representando o número de vezes que KiloMan é atingido.'''])
        ],

    2484:[
        ("Descrição", ['''No século XXII, uma doença devastadora atingiu mais da metade da população mundial. O governo está desesperado em busca de uma cura, pois há um grande risco de que a doença dizime toda a população. Os hospitais estão lotados e a aflição no olhar das pessoas é notável.\nNesta época, poucas pessoas têm acesso livre à internet, mas você é uma delas. Ao vasculhar a rede, você encontrou alguns textos dispersos sobre um amuleto de uma palavra mágica escrita em forma de um triângulo que cura doenças letais. Incrédulo mas esperançoso, você se lembrou de que a biblioteca do Sr. Severino tinha um livro um tanto inusitado, com a seguinte capa:''', "<img>", ''' \nEntão, você foi imediatamente à biblioteca. Chegando lá, ao ler somente o prefácio do livro, já confirmou tudo o que viu sobre os amuletos na rede, e em seguida, deu a si mesmo uma missão: espalhar palavras mágicas na rede em forma de um triângulo a fim de alertar as pessoas de que pode haver uma cura para a doença. Por consequência, se forem construídos amuletos em massa com palavras mágicas e estes forem entregues às pessoas, a doença pode ser aniquilada e a população, salva.\nPara completar tal missão, você deverá começar pelo passo mais simples: escrever um programa que receba uma palavra e a transforme em um triângulo, tal como na capa do livro.''']),
        ("Entrada", ['''A entrada contém vários casos de teste. Cada caso de teste é composto por uma palavra de 2 até 100 caracteres e sem espaços. A entrada termina com EOF (fim de arquivo).''']),
        ("Saída", ['''Para cada caso de teste, imprima a palavra recebida em forma de um triângulo e lembre-se de deixar um espaço em branco entre cada letra, mas não deixe espaço em branco após a última letra de cada linha. Imprima uma linha em branco após cada caso de teste, inclusive após o último.'''])
        ],

    2974:[
        ("Descrição", ['''Em um porão escuro, há uma caixa de madeira com soluções impressas para todas as tarefas deste concurso. No entanto, o porão tem paredes grossas e uma porta, e uma fechadura na porta. Na fechadura existem n barras de ferro horizontais e em cada uma das barras há uma palavra com letras de igual largura. Cada barra pode ser movida independentemente para a esquerda ou direita para uma ou mais larguras de uma letra. Há pelo menos uma letra que é comum a todas as palavras. Portanto, as barras podem ser alinhadas de modo que haja uma linha vertical de n letras idênticas acima uma da outra (cada letra em uma barra). Para destrancar a porta, as barras devem ser posicionadas de tal forma que haja um número máximo de linhas verticais consecutivas.''','''Você está naturalmente interessado em escrever um programa que resolva esse problema.''']),
        ("Entrada", ['''A primeira linha contém um inteiro n, o número de barras, com n <= 1000. Em cada uma das próximas n linhas, há uma palavra correspondente a uma das barras. As palavras contém somente letras maiúsculas, e possuem no mínimo 1 e no máximo 100 caracteres.''']),
        ("Saída", ['''Uma string de comprimento máximo, que aparece em cada palavra como uma sequência de letras consecutivas. Se houver mais de uma solução, você deverá imprimir a mais à esquerda.'''])
        ],
    
    2544:[
        ("Descrição", ['''Em um porão escuro, há uma caixa de madeira com soluções impressas para todas as tarefas deste concurso. No entanto, o porão tem paredes grossas e uma porta, e uma fechadura na porta. Na fechadura existem n barras de ferro horizontais e em cada uma das barras há uma palavra com letras de igual largura. Cada barra pode ser movida independentemente para a esquerda ou direita para uma ou mais larguras de uma letra. Há pelo menos uma letra que é comum a todas as palavras. Portanto, as barras podem ser alinhadas de modo que haja uma linha vertical de n letras idênticas acima uma da outra (cada letra em uma barra). Para destrancar a porta, as barras devem ser posicionadas de tal forma que haja um número máximo de linhas verticais consecutivas.''','''Você está naturalmente interessado em escrever um programa que resolva esse problema.''']),
        ("Entrada", ['''A primeira linha contém um inteiro n, o número de barras, com n <= 1000. Em cada uma das próximas n linhas, há uma palavra correspondente a uma das barras. As palavras contém somente letras maiúsculas, e possuem no mínimo 1 e no máximo 100 caracteres.''']),
        ("Saída", ['''Uma string de comprimento máximo, que aparece em cada palavra como uma sequência de letras consecutivas. Se houver mais de uma solução, você deverá imprimir a mais à esquerda.'''])
        ],
    
    2693:[
        ("Descrição", ['''Em um porão escuro, há uma caixa de madeira com soluções impressas para todas as tarefas deste concurso. No entanto, o porão tem paredes grossas e uma porta, e uma fechadura na porta. Na fechadura existem n barras de ferro horizontais e em cada uma das barras há uma palavra com letras de igual largura. Cada barra pode ser movida independentemente para a esquerda ou direita para uma ou mais larguras de uma letra. Há pelo menos uma letra que é comum a todas as palavras. Portanto, as barras podem ser alinhadas de modo que haja uma linha vertical de n letras idênticas acima uma da outra (cada letra em uma barra). Para destrancar a porta, as barras devem ser posicionadas de tal forma que haja um número máximo de linhas verticais consecutivas.''','''Você está naturalmente interessado em escrever um programa que resolva esse problema.''']),
        ("Entrada", ['''A primeira linha contém um inteiro n, o número de barras, com n <= 1000. Em cada uma das próximas n linhas, há uma palavra correspondente a uma das barras. As palavras contém somente letras maiúsculas, e possuem no mínimo 1 e no máximo 100 caracteres.''']),
        ("Saída", ['''Uma string de comprimento máximo, que aparece em cada palavra como uma sequência de letras consecutivas. Se houver mais de uma solução, você deverá imprimir a mais à esquerda.'''])
        ],

    2496:[
        ("Descrição", ['''Em um porão escuro, há uma caixa de madeira com soluções impressas para todas as tarefas deste concurso. No entanto, o porão tem paredes grossas e uma porta, e uma fechadura na porta. Na fechadura existem n barras de ferro horizontais e em cada uma das barras há uma palavra com letras de igual largura. Cada barra pode ser movida independentemente para a esquerda ou direita para uma ou mais larguras de uma letra. Há pelo menos uma letra que é comum a todas as palavras. Portanto, as barras podem ser alinhadas de modo que haja uma linha vertical de n letras idênticas acima uma da outra (cada letra em uma barra). Para destrancar a porta, as barras devem ser posicionadas de tal forma que haja um número máximo de linhas verticais consecutivas.''','''Você está naturalmente interessado em escrever um programa que resolva esse problema.''']),
        ("Entrada", ['''A primeira linha contém um inteiro n, o número de barras, com n <= 1000. Em cada uma das próximas n linhas, há uma palavra correspondente a uma das barras. As palavras contém somente letras maiúsculas, e possuem no mínimo 1 e no máximo 100 caracteres.''']),
        ("Saída", ['''Uma string de comprimento máximo, que aparece em cada palavra como uma sequência de letras consecutivas. Se houver mais de uma solução, você deverá imprimir a mais à esquerda.'''])
        ],
    
    2460:[
        ("Descrição", ['''Em um porão escuro, há uma caixa de madeira com soluções impressas para todas as tarefas deste concurso. No entanto, o porão tem paredes grossas e uma porta, e uma fechadura na porta. Na fechadura existem n barras de ferro horizontais e em cada uma das barras há uma palavra com letras de igual largura. Cada barra pode ser movida independentemente para a esquerda ou direita para uma ou mais larguras de uma letra. Há pelo menos uma letra que é comum a todas as palavras. Portanto, as barras podem ser alinhadas de modo que haja uma linha vertical de n letras idênticas acima uma da outra (cada letra em uma barra). Para destrancar a porta, as barras devem ser posicionadas de tal forma que haja um número máximo de linhas verticais consecutivas.''','''Você está naturalmente interessado em escrever um programa que resolva esse problema.''']),
        ("Entrada", ['''A primeira linha contém um inteiro n, o número de barras, com n <= 1000. Em cada uma das próximas n linhas, há uma palavra correspondente a uma das barras. As palavras contém somente letras maiúsculas, e possuem no mínimo 1 e no máximo 100 caracteres.''']),
        ("Saída", ['''Uma string de comprimento máximo, que aparece em cada palavra como uma sequência de letras consecutivas. Se houver mais de uma solução, você deverá imprimir a mais à esquerda.'''])
        ],
    
    2343:[
        ("Descrição", ['''Em um porão escuro, há uma caixa de madeira com soluções impressas para todas as tarefas deste concurso. No entanto, o porão tem paredes grossas e uma porta, e uma fechadura na porta. Na fechadura existem n barras de ferro horizontais e em cada uma das barras há uma palavra com letras de igual largura. Cada barra pode ser movida independentemente para a esquerda ou direita para uma ou mais larguras de uma letra. Há pelo menos uma letra que é comum a todas as palavras. Portanto, as barras podem ser alinhadas de modo que haja uma linha vertical de n letras idênticas acima uma da outra (cada letra em uma barra). Para destrancar a porta, as barras devem ser posicionadas de tal forma que haja um número máximo de linhas verticais consecutivas.''','''Você está naturalmente interessado em escrever um programa que resolva esse problema.''']),
        ("Entrada", ['''A primeira linha contém um inteiro n, o número de barras, com n <= 1000. Em cada uma das próximas n linhas, há uma palavra correspondente a uma das barras. As palavras contém somente letras maiúsculas, e possuem no mínimo 1 e no máximo 100 caracteres.''']),
        ("Saída", ['''Uma string de comprimento máximo, que aparece em cada palavra como uma sequência de letras consecutivas. Se houver mais de uma solução, você deverá imprimir a mais à esquerda.'''])
        ],
    
    2310:[
        ("Descrição", ['''Em um porão escuro, há uma caixa de madeira com soluções impressas para todas as tarefas deste concurso. No entanto, o porão tem paredes grossas e uma porta, e uma fechadura na porta. Na fechadura existem n barras de ferro horizontais e em cada uma das barras há uma palavra com letras de igual largura. Cada barra pode ser movida independentemente para a esquerda ou direita para uma ou mais larguras de uma letra. Há pelo menos uma letra que é comum a todas as palavras. Portanto, as barras podem ser alinhadas de modo que haja uma linha vertical de n letras idênticas acima uma da outra (cada letra em uma barra). Para destrancar a porta, as barras devem ser posicionadas de tal forma que haja um número máximo de linhas verticais consecutivas.''','''Você está naturalmente interessado em escrever um programa que resolva esse problema.''']),
        ("Entrada", ['''A primeira linha contém um inteiro n, o número de barras, com n <= 1000. Em cada uma das próximas n linhas, há uma palavra correspondente a uma das barras. As palavras contém somente letras maiúsculas, e possuem no mínimo 1 e no máximo 100 caracteres.''']),
        ("Saída", ['''Uma string de comprimento máximo, que aparece em cada palavra como uma sequência de letras consecutivas. Se houver mais de uma solução, você deverá imprimir a mais à esquerda.'''])
        ],
}